from django.shortcuts import render

# Create your views here.

def index(request):
    data = {
        'title': 'Заглавная страница',
        'content': "'Però perquè entenguis don tot error nascut és el plaer d'acusar i lloar el dolor, obriré tot i explicaré allò que va dir aquell inventor de la veritat i, per dir-ho, l'arquitecte. de la vida beneïda. Perquè ningú rebutja, odia ni defuig el plaer, perquè és el plaer mateix, sinó perquè els grans dolors resulten daquells que no saben com seguir el plaer per la raó; però no es donen temps d'aquesta mena perquè busqui algun gran. plaer pel treball i el dolor. Perquè, en el més mínim grau, qui de nosaltres fa algun exercici físic laboriós, excepte per treure'n algun avantatge? Però qui pot condemnar amb raó aquell que vol estar en aquell plaer, que cap molèstia aconsegueix? Però, d'altra banda, tots dos els acusem i els considerem més dignes de just odi, els quals, calmats per l'adulació dels plaers presents, i corromputs, no preveuen quins dolors i quins problemes rebran, encegats pel desig; I la distinció entre aquestes coses és fàcil i fàcil. Perquè en el temps lliure, quan l'elecció d'escollir és lliure per a nosaltres, i quan res no ens impedeix poder fer allò que més plau, cal assumir cada plaer, evitar qualsevol dolor. Però durant certs temps, succeirà amb freqüència, ja sigui pels oficis necessaris o per les necessitats de la vida, que tots dos plaers s'han de repudiar i no acceptar les molèsties. En conseqüència, l'elecció d'aquestes coses està lligada aquí al savi, de manera que o rebutjant els plaers n'obté d'altres de més grans, o pot fer retrocedir els més severament suportats pels dolors perdurables.'"
    }
    return render(request, 'main/index.html', data)

def about(request):
    data = {
        'title': 'О нас',
        'content': ['Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit, amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.']
    }
    return render(request, 'main/about.html', data)

