# Generated by Django 4.0 on 2021-12-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
